import React, { useState } from 'react';
import {
    Download,
    FileText,
    Copy,
    Check,
    Rocket,
    AlertCircle,
    Cpu
} from 'lucide-react';
import { AEOPlaybook } from '../../types';

interface PlaybookViewProps {
    playbook: AEOPlaybook;
    brandName?: string;
}

export const PlaybookView: React.FC<PlaybookViewProps> = ({ playbook, brandName }) => {
    const [copiedAction, setCopiedAction] = useState<number | null>(null);

    const copyActionToClipboard = (action: typeof playbook.actions[0], idx: number) => {
        const text = `## ${action.title}\n\n${action.description}\n\nImpact: ${action.impact} | Effort: ${action.effort}`;
        navigator.clipboard.writeText(text);
        setCopiedAction(idx);
        setTimeout(() => setCopiedAction(null), 2000);
    };

    const exportPlaybookAsMarkdown = () => {
        const md = `# AEO Optimization Playbook${brandName ? ` for ${brandName}` : ''}

## Executive Summary

${playbook.summary}

## Recommended Actions

${playbook.actions.map((a, i) => `### ${i + 1}. ${a.title}

${a.description}

- **Impact:** ${a.impact}
- **Effort:** ${a.effort}
`).join('\n')}

## Knowledge Gaps to Address

${playbook.knowledge_gaps.length > 0
                ? playbook.knowledge_gaps.map((g, i) => `${i + 1}. ${g}`).join('\n')
                : 'No specific gaps identified.'}

---
*Generated by AEO Vision*
`;
        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `aeo-playbook${brandName ? `-${brandName.toLowerCase().replace(/\s+/g, '-')}` : ''}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const exportActionsAsJSON = () => {
        const tasks = playbook.actions.map((a, i) => ({
            id: i + 1,
            title: a.title,
            description: a.description,
            priority: a.impact === 'High' ? 'high' : a.impact === 'Medium' ? 'medium' : 'low',
            effort: a.effort.toLowerCase(),
            status: 'todo',
            category: 'aeo-optimization',
        }));
        const blob = new Blob([JSON.stringify(tasks, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'aeo-tasks.json';
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-10">
            {/* Export Actions Bar */}
            <div className="flex flex-wrap gap-3 justify-end">
                <button
                    onClick={exportPlaybookAsMarkdown}
                    className="flex items-center gap-2 px-4 py-2 bg-gray-100 hover:bg-gray-200 rounded-xl text-sm font-semibold text-gray-700 transition"
                >
                    <Download className="w-4 h-4" />
                    Export as Markdown
                </button>
                <button
                    onClick={exportActionsAsJSON}
                    className="flex items-center gap-2 px-4 py-2 bg-indigo-100 hover:bg-indigo-200 rounded-xl text-sm font-semibold text-indigo-700 transition"
                >
                    <FileText className="w-4 h-4" />
                    Export Tasks (JSON)
                </button>
            </div>

            <div className="bg-white/70 backdrop-blur-md rounded-3xl border border-gray-100 p-10 shadow-sm relative overflow-hidden">
                <div className="absolute top-0 right-0 p-10 opacity-5 pointer-events-none">
                    <Cpu className="w-40 h-40 text-indigo-600" />
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                    <FileText className="text-indigo-600 w-7 h-7" />
                    Strategic Executive Summary
                </h3>
                <p className="text-gray-600 leading-relaxed text-lg max-w-4xl relative z-10">
                    {playbook.summary}
                </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="space-y-6">
                    <h3 className="text-xl font-bold text-gray-900 px-2 flex items-center gap-2">
                        <Rocket className="text-indigo-600 w-5 h-5" />
                        Recommended Actions ({playbook.actions.length})
                    </h3>
                    {playbook.actions.map((action, idx) => (
                        <div key={idx} className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm hover:border-indigo-200 transition-all group relative hover:-translate-y-1 hover:shadow-md">
                            <button
                                onClick={() => copyActionToClipboard(action, idx)}
                                className="absolute top-4 right-4 p-2 text-gray-300 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition opacity-0 group-hover:opacity-100"
                                title="Copy to clipboard"
                            >
                                {copiedAction === idx ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
                            </button>
                            <div className="flex items-start justify-between mb-4 pr-10">
                                <h4 className="font-bold text-gray-900 group-hover:text-indigo-600 transition-colors">{action.title}</h4>
                            </div>
                            <div className="flex gap-2 mb-3">
                                <span className={`text-[10px] font-bold uppercase tracking-widest px-2 py-1 rounded-lg ${action.impact === 'High' ? 'bg-emerald-50 text-emerald-600' : action.impact === 'Medium' ? 'bg-amber-50 text-amber-600' : 'bg-gray-50 text-gray-500'}`}>
                                    {action.impact} Impact
                                </span>
                                <span className={`text-[10px] font-bold uppercase tracking-widest px-2 py-1 rounded-lg ${action.effort === 'Easy' ? 'bg-emerald-50 text-emerald-600' : action.effort === 'Moderate' ? 'bg-amber-50 text-amber-600' : 'bg-rose-50 text-rose-600'}`}>
                                    {action.effort} Effort
                                </span>
                            </div>
                            <p className="text-gray-500 text-sm leading-relaxed">{action.description}</p>
                        </div>
                    ))}
                </div>

                <div className="space-y-6">
                    <h3 className="text-xl font-bold text-gray-900 px-2 flex items-center gap-2">
                        <AlertCircle className="text-rose-500 w-5 h-5" />
                        Detected Knowledge Gaps ({playbook.knowledge_gaps.length})
                    </h3>
                    <div className="bg-rose-50/50 backdrop-blur-sm rounded-3xl p-8 border border-rose-100 h-full">
                        <p className="text-rose-800 text-sm font-medium mb-6">
                            AI models identified these gaps or outdated facts during analysis. Addressing these in your technical docs, FAQ, and PR will improve AEO performance.
                        </p>
                        <ul className="space-y-4">
                            {playbook.knowledge_gaps.map((gap, idx) => (
                                <li key={idx} className="flex gap-3 items-start bg-white p-4 rounded-xl shadow-sm border border-rose-50">
                                    <div className="w-5 h-5 rounded-full bg-rose-100 flex-shrink-0 flex items-center justify-center text-rose-600 font-bold text-[10px]">!</div>
                                    <span className="text-gray-700 text-sm leading-snug">{gap}</span>
                                </li>
                            ))}
                            {playbook.knowledge_gaps.length === 0 && (
                                <li className="text-rose-500 italic text-sm">No specific gaps identified. AI appears to have up-to-date data.</li>
                            )}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    );
};
